version: "3.8"
services:
    # php service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=production
        environment:
            - APP_ENV=production
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
